//	This file was generated by St4mpede 2015-11-02 20:57:35Z.

public class User
{
	public System.Int32 UserId { get; set; }
	public System.String UserName { get; set; }
	public System.Char HashedPassword { get; set; }
	public System.DateTime LastLoggedOnDatetime { get; set; }
}
