//	This file was generated by St4mpede.Surface 2016-05-21 00:54:34Z.

namespace TheDal.Surface
{
	using System.Collections.Generic;
	using System.Linq;
	using Dapper;

	/// <summary> This is the Surface for the Project table.
	/// </summary>
	public class ProjectSurface
	{
	
		public ProjectSurface()
		{
		}
	
		/// <summary> This method is used for adding a new record in the database.
		/// </summary>
		private TheDAL.Poco.Project Add( TheDAL.CommitScope context, System.String name )
		{
			//TODO:OF:TBA.
			return null;
		}
	
		/// <summary> This method is used for adding a new record in the database.
		/// <para>St4mpede guid:{759FBA46-A462-4E4A-BA2B-9B5AFDA572DE}</para>
		/// </summary>
		private TheDAL.Poco.Project Add( TheDAL.CommitScope context, TheDAL.Poco.Project project )
		{
			const string Sql = @"
				Insert Into Project
				(
					Name
				)
				Values
				(
					@Name
				)
				Select * From Project Where ProjectId = Scope_Identity()";
			var ret = context.Connection.Query<TheDAL.Poco.Project>(
				Sql, 
				new { /*...*/ },
				context.Transaction,
				false, null, null);
			return ret.Single();
		}
	
		/// <summary> This method is used for deleting a record.
		/// </summary>
		public void Delete( TheDAL.CommitScope context, TheDAL.Poco.Project project )
		{
			//TODO:OF:TBA. =>get or throw exception.
		}
	
		/// <summary> This method is used for deleting a record by its primary key.
		/// </summary>
		public void DeleteById( TheDAL.CommitScope context, System.Int32 projectId )
		{
			//TODO:OF:TBA. =>get or throw exception.
		}
	
		/// <summary> This method returns every record for this table/surface.
		/// Do not use it on too big tables.
		/// </summary>
		public IList<TheDAL.Poco.Project> GetAll( TheDAL.CommitScope context )
		{
			//TODO:OF:TBA.
			return null;
		}
	
		/// <summary> This method is used for getting a record but its Id/primary key.
		/// If nothing is found an exception is thrown. If you want to get null back use LoadById <see cref="LoadById"> instead.
		/// </summary>
		public TheDAL.Poco.Project GetById( TheDAL.CommitScope context, System.Int32 projectId )
		{
			//TODO:OF:TBA. =>get or throw exception.
			return null;
		}
	
		/// <summary> This method is used for getting a record but its Id/primary key.
		/// If nothing is found an null is returned. If you want to throw an exception use GetById <see cref="GetById"> instead.
		/// </summary>
		public TheDAL.Poco.Project LoadById( TheDAL.CommitScope context, System.Int32 projectId )
		{
			//TODO:OF:TBA. =>get or return null.
			return null;
		}
	
		/// <summary> This method is used for updating an existing record in the database.
		/// </summary>
		private TheDAL.Poco.Project Update( TheDAL.CommitScope context, System.Int32 projectId, System.String name )
		{
			//TODO:OF:TBA.
			return null;
		}
	
		/// <summary> This method is used for updating an existing record in the database.
		/// </summary>
		private TheDAL.Poco.Project Update( TheDAL.CommitScope context, TheDAL.Poco.Project project )
		{
			//TODO:OF:TBA.
			return null;
		}
	
		/// <summary> This method is used for creating a new or  updating an existing record in the database.
		/// If the primary key is 0 (zero) we know it is a new record and try to add it. Otherwise we try to update the record.
		/// </summary>
		public TheDAL.Poco.Project Upsert( TheDAL.CommitScope context, System.Int32 projectId, System.String name )
		{
			//TODO:OF:TBA. =>if( return 0 == primarykey ? Add(...) : Update(...)
			return null;
		}
	
		/// <summary> This method is used for creating a new or  updating an existing record in the database.
		/// If the primary key is 0 (zero) we know it is a new record and try to add it. Otherwise we try to update the record.
		/// </summary>
		public TheDAL.Poco.Project Upsert( TheDAL.CommitScope context, TheDAL.Poco.Project project )
		{
			//TODO:OF:TBA. =>if( return 0 == primarykey ? Add(...) : Update(...)
			return null;
		}
	}
}
