//	This file was generated by St4mpede.Surface 2016-05-19 15:24:03Z.

/// <summary> This is the Surface for the User table.
/// </summary>
public class UserSurface
{

	public UserSurface()
	{
	}

	/// <summary> This method is used for adding a new record in the database.
	/// </summary>
	private TheDAL.Poco.User Add( System.String userName, System.String hashedPassword, System.DateTime lastLoggedOnDatetime )
	{
		//TODO:OF:TBA.
		return null;
	}

	/// <summary> This method is used for updating an existing record in the database.
	/// </summary>
	private TheDAL.Poco.User Update( System.Int32 userId, System.String userName, System.String hashedPassword, System.DateTime lastLoggedOnDatetime )
	{
		//TODO:OF:TBA.
		return null;
	}

	/// <summary> This method is used for creating a new or  updating an existing record in the database.
	/// If the primary key is 0 (zero) we know it is a new record and try to add it. Otherwise we try to update the record.
	/// </summary>
	public TheDAL.Poco.User Upsert( System.Int32 userId, System.String userName, System.String hashedPassword, System.DateTime lastLoggedOnDatetime )
	{
		//TODO:OF:TBA. =>if( return 0 == primarykey ? Add(...) : Update(...)
		return null;
	}
}
