//	This file was generated by St4mpede 2015-12-02 21:30:10Z.

public partial class Customer
{
	/// <summary> This property is part of the primary key.
	/// </summary>
	public System.Int32 CustomerID{ get; set; }

	public System.String Name{ get; set; }

	/// <summary> Default constructor needed for instance for de/serialising.
	/// </summary>
	public Customer()
	{
	}

	/// <summary> This constructor takes all properties as parameters.
	/// </summary>
	public Customer( System.Int32 customerID, System.String name )
	{
		this.CustomerID = customerID;
		this.Name = name;
	}

	/// <summary> This constructor takes all properties but primary keys as parameters.
	/// </summary>
	public Customer( System.String name )
	{
		this.Name = name;
	}
}
