//	This file was generated by St4mpede 2015-11-22 21:40:55Z.

public partial class Customer
{
	/// <summary> This property is part of the primary key.
	/// </summary>
	public System.Int32 CustomerID{ get; set; }

	public System.String Name{ get; set; }

	/// <summary> Default constructor needed for instance for de/serialising.
	/// </summary>
	public Customer()
	{
	}

	/// <summary> This constructor takes all properties as parameters.
	/// </summary>
	public Customer()
	{
	}

	/// <summary> This constructor takes all properties, except primary key(s) as parameters.
	/// </summary>
	public Customer()
	{
	}
}
