//	This file was generated by St4mpede 2015-11-07 21:17:26Z.

public class Customer
{
	/// <summary>This property is (part of) primary key.
	/// </summary>
	public System.Int32 CustomerID { get; set; }
	public System.String Name { get; set; }
}
