//	This file was generated by St4mpede 2015-10-27 22:38:33Z.

public class User
{
	public System.Int32 UserId { get; set; }
	public System.String UserName { get; set; }
	public System.Char HashedPassword { get; set; }
	public System.DateTime LastLoggedOnDatetime { get; set; }
}
