//	This file was generated by St4mpede 2015-11-19 19:47:18Z.

public class User
{
	public System.Int32 UserId{ get; set; }

	public System.String UserName{ get; set; }

	public System.Char HashedPassword{ get; set; }

	public System.DateTime LastLoggedOnDatetime{ get; set; }

}
