//	This file was generated by St4mpede 2015-11-07 21:17:26Z.

public class User
{
	/// <summary>This property is (part of) primary key.
	/// </summary>
	public System.Int32 UserId { get; set; }
	public System.String UserName { get; set; }
	public System.Char HashedPassword { get; set; }
	public System.DateTime LastLoggedOnDatetime { get; set; }
}
